### ISSUE TITLE
New version release with Pub/Sub emulator support

### ISSUE THREAD

**Issue by anguillanneuf** [GoogleCloudPlatform/functions-framework-java#104]
Would like to request a new version release with https://github.com/GoogleCloudPlatform/functions-framework-java/pull/98. The last release was almost a year ago.

@eamonnmcmanus @grant

**Comment by grant** [comment]
CC @matthewrobertson

**Comment by anguillanneuf** [comment]
Fixed in 5fd42a74d16ea087987fc2cb517ef861778fd1b1

Fixed in release 1.0.3: https://github.com/GoogleCloudPlatform/functions-framework-java/releases/tag/java-function-invoker-parent-1.0.3
