### ISSUE TITLE
`-Drun.functionTarget=...` does not override pom.xml

### ISSUE THREAD

**Issue by averikitsch** [GoogleCloudPlatform/functions-framework-java#126]
I expect if I run `mvn function:run -Drun.functionTarget=your.package.yourFunction` would override any `<funtionTarget>` in my pom.xml.

```
<plugin>
        <groupId>com.google.cloud.functions</groupId>
        <artifactId>function-maven-plugin</artifactId>
        <version>0.10.0</version>
        <configuration>
          <functionTarget>functions.LogCloudEvent</functionTarget>
        </configuration>
</plugin>
```

Currently, running `mvn function:run -Drun.functionTarget=your.package.yourFunction` with the above plugin would end up running `functions.LogCloudEvent`.

**Comment by ludoch** [comment]
I think unfortunately it is the default mvn behavior...
For ex: https://github.com/spotify/docker-maven-plugin/issues/367
