### ISSUE TITLE
Moving GoogleCloudPlatform/native-image-support-java's cloud-functions-sample to this repository

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/functions-framework-java#130]
We're relocating the sample code (Java) in https://github.com/GoogleCloudPlatform/native-image-support-java/tree/master/native-image-samples/native-image-samples-client-library to the corresponding library repositories.

I'm taking https://github.com/GoogleCloudPlatform/native-image-support-java/tree/master/native-image-samples/native-image-samples-client-library/cloud-functions-sample and the sample is for the following libraries:

```
    <!-- Function Framework Deps -->
    <dependency>
      <groupId>com.google.cloud.functions</groupId>
      <artifactId>functions-framework-api</artifactId>
      <version>1.0.4</version>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>com.google.cloud.functions.invoker</groupId>
      <artifactId>java-function-invoker</artifactId>
      <version>1.1.0</version>
    </dependency>
```

They are developed in this repository (but this repository doesn't seem to have sample code)

I'm thinking to create a pull request to migrate the sample to this repository with a test. If you have some ideas for better locations, please let me know.

CC: @mpeddada1

**Comment by suztomo** [comment]
It doesn't work.

**Comment by ludoch** [comment]
Not sure there is a supported native image for Cloud function, so we do not need to carry over this sample.

**Comment by suztomo** [comment]
No, it doesn't work for Cloud Functions and thus it doesn't make sense to add the sample. Got the same answer from Éamonn and Annie as well. Closing.
