### ISSUE TITLE
function-maven-plugin add support for --set-build-env-vars

### ISSUE THREAD

**Issue by cranberrysoft** [GoogleCloudPlatform/functions-framework-java#131]
Currently, it is not possible to set a build env for the Maven plugin.

This is especially a problem when you have a multi-module Maven project and you need to tell Buildpack which module you want to include by providing `--set-build-env-vars GOOGLE_BUILDABLE="my-module"`

**Comment by ludoch** [comment]
We should now do a new release, right?
