### ISSUE TITLE
Consider bumping Jetty version

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/functions-framework-java#132]
Jetty has newer 9.4 release, we can bump in https://github.com/GoogleCloudPlatform/functions-framework-java/blob/1863d1314d95b57a53003f2cf83f1221f46b2502/invoker/core/pom.xml to be the latest (already used in GAE Java)

**Comment by anniefu** [comment]
Looks like this was self-fixed. Thanks!

**Comment by ludoch** [comment]
I still see an old 9.4 release used in https://github.com/GoogleCloudPlatform/functions-framework-java/blob/master/invoker/core/pom.xml#L100
We want to keep the 9.4 versions, but need to keep up with minor releases like in GAE
