### ISSUE TITLE
Is there any plan to support opentelemetry-javaagent auto-instrumention 

### ISSUE THREAD

**Issue by xinglsh6937** [GoogleCloudPlatform/functions-framework-java#142]
I am building serverless applications with google java framework function, and want to collect function trace data automatically. I found opentelemetry-javaagent auto-instrumention, but this framework is not supported by it. So Is there any support plan ?

**Comment by anniefu** [comment]
Tracing can be added to your function or application using the standard client libraries: https://cloud.google.com/trace/docs/client-libraries

There's no plan to do any automatic tracing within Functions Framework at this time.
