### ISSUE TITLE
How to deploy the java function to serverless platform

### ISSUE THREAD

**Issue by duchnguyen** [GoogleCloudPlatform/functions-framework-java#16]
Hi Support team,

I would like to develop a java background function to listen on firestore changes of a given endpoint. Such as: Object creation, object update, ... Can you please guide me steps to implement this? And especially how to deploy my function to cloud-function?

Many Thanks,
Duc

**Comment by grant** [comment]
Hey Duc, that's a great question. Right now we don't have any guides for this framework.

We should provide a guide for deploying this framework to Cloud Run.
(CC @saturnism, this would make a great blogpost!)

**Comment by duchnguyen** [comment]
Thanks for your support @grant .
