### ISSUE TITLE
1.0.0-alpha-2-rc4 not in Maven central

### ISSUE THREAD

**Issue by graemerocher** [GoogleCloudPlatform/functions-framework-java#17]
The `1.0.0-alpha-2-rc4` release hasn't been synced to Maven central, could this be done?

**Comment by graemerocher** [comment]
Bump. @glaforge @amonnmcmanus any news on this one?

**Comment by meltsufin** [comment]
Are you looking for `functions-framework-api` or `functions-framework-invoker`? They have different versions now.

**Comment by graemerocher** [comment]
A gotcha.. so the API hasn't changed, only the invoker
