### ISSUE TITLE
Invoker.stopServer method is missing

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/functions-framework-java#18]
We're using the Invoker class in our integration tests. However, we find that we're unable to shutdown the Jetty server because there is no `Invoker.stopServer()` method.

**Comment by eamonnmcmanus** [comment]
As a workaround, you could create the Invoker in a subprocess, then kill that when the test is over. That's what we do in the invoker's own [integration tests](https://github.com/GoogleCloudPlatform/functions-framework-java/blob/master/invoker/core/src/test/java/com/google/cloud/functions/invoker/IntegrationTest.java#L610) for example. However, it does seem that we should make something like `stopServer()` or `close()` available for in-process tests.

**Comment by lesv** [comment]
For testing, it's good if we can follow this kind of pattern:
https://www.baeldung.com/maven-integration-test

**Comment by lesv** [comment]
So the Invoker would have a `start` similar to jetty:start` that in started during the `pre-integration-test` phase, then run the test, and stop w/ a `stop` similar to `jetty:stop` that is executed during the `post-integration-test` phase.
