### ISSUE TITLE
Where is the 0.11.0 function-maven-plugin deployed ?

### ISSUE THREAD

**Issue by Chuckame** [GoogleCloudPlatform/functions-framework-java#208]
As the title said, I did not found the 0.11.0 (but only 0.10.1) in multiple mvn repositories ([mvnrepository.com](https://mvnrepository.com/artifact/com.google.cloud.functions/function-maven-plugin), [central.sonatype.com](https://central.sonatype.com/artifact/com.google.cloud.functions/function-maven-plugin)). Where is it ?

0.11.0 is including gen2 that could be useful !

Also maybe update the readme to be able to find it ? 😄

**Comment by HKWinterhalter** [comment]
Hi @Chuckame, thanks for bringing this up! I have fixed the issue so you can now find the 0.11.0 release: [central.sonatype.com](https://central.sonatype.com/artifact/com.google.cloud.functions/function-maven-plugin). I don't see it on mvnrepository yet, so it may not have re-indexed yet.
