### ISSUE TITLE
BackgroundFunction should support throwing any exception

### ISSUE THREAD

**Issue by ace-n** [GoogleCloudPlatform/functions-framework-java#21]
Right now, any exception thrown by. a `BackgroundFunction` must be a subclass of `RuntimeException`.

In order to please the compiler, we have to use code like this:
```java
try {
  // Not a descendant of RuntimeException
  throwAnIOException();
} catch (IOException e) {
  throw new RuntimeException(e);
}
```

The easiest solution here is probably to modify the `BackgroundFunction` function signature to allow throwing any [descendant of] `Exception`.

cc @glaforge @kurtisvg @saturnism

**Comment by saturnism** [comment]
@ace-n is this related to a sample?

**Comment by eamonnmcmanus** [comment]
Yes, I had intended to adjust this. Making people catch and wrap exceptions is pointless and annoying.
