### ISSUE TITLE
Requesting `/favicon.ico` or `/robots.txt` invokes function, although it shouldn't according to doc 

### ISSUE THREAD

**Issue by alsoba13** [GoogleCloudPlatform/functions-framework-java#225]
# Expected behaviour
According to [Functions framework documentation](https://github.com/GoogleCloudPlatform/functions-framework#url-space), requests to `/favicon.ico` and `/robots.txt` should return a 404 status without calling the function:

> Note that the framework must listen to all inbound paths (.*) and route these requests to the function, with the following exceptions:
> * `/robots.txt` - must respond with 404 without invoking function
> * `/favicon.ico` - must response with 404 without invoking function

# Actual behaviour
When requesting a `/favicon.ico` or `/robots.txt`, a 404 status is returned, but the function is _actually invoked_, with all its possible side effects.

# Reproduction
1. Take the Hello World example from this repository, but write directly to stdout:
```java
package com.example;

import com.google.cloud.functions.HttpFunction;
import com.google.cloud.functions.HttpRequest;
import com.google.cloud.functions.HttpResponse;

public class HelloWorld implements HttpFunction {
  @Override
  public void service(HttpRequest request, HttpResponse response)
      throws Exception {
    System.out.println("Hello World! Path: " + request.getPath());
  }
}
```
2. Run function:
```bash
./gradlew runFunction -Prun.functionTarget=com.example.HelloWorld
```
3. Curl to `/favicon.ico`:
```
curl localhost:8080/favicon.ico
```
4. See the result in the console to check that the function is executed with `/favicon.ico`:
```
Hello World! Path: /favicon.ico
```

# Possible fix
I believe that the bug is at the `NotFoundHandler` class, that executes the `super` after writing the 404 error. I am not familiar with Jetty's handlers API, but we may see that other jetty handlers ([InetAccessHandler.java](https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-server/src/main/java/org/eclipse/jetty/server/handler/InetAccessHandler.java#L212-L229)) do `return` right after generating the `sendError`.

PR for this: https://github.com/GoogleCloudPlatform/functions-framework-java/pull/226

# Related
* Most of the other Functions frameworks have a special handler for this (except for golang), and even nodejs framework has deal with a conceptually similar issue: https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/191
* For production environment, there exist some workaround but it needs to be very precisely executed, otherwise some odd errors (502 codes) will occur. I can give more detail if someone is interested.

**Comment by HKWinterhalter** [comment]
Thanks for finding and reporting on this! I have approved PR #226
