### ISSUE TITLE
Can we deploy remote function via any SDKs?

### ISSUE THREAD

**Issue by wycmiko** [GoogleCloudPlatform/functions-framework-java#246]
Hi Team,
Can we deploy remote functions via any SDKs? It seems like we need to deploy funcs manually via `gcloud`, any automated solutions for it?

**Comment by alsoba13** [comment]
What do you mean by SDK? Isn't `gcloud` an SDK?
There's a lot of people automating deployments through GitHub actions. There you may use gcloud, terraform or any tool (including other's GH actions)

**Comment by HKWinterhalter** [comment]
Hi @wycmiko, yes, Google Cloud has SDKs for various languages and services. 

Here is the reference for Cloud Functions for Java: https://cloud.google.com/java/docs/reference/google-cloud-functions/latest/overview

Also see: https://cloud.google.com/functions/docs/apis/libraries#client-libraries-resources-java and https://cloud.google.com/sdk/?hl=en.
