### ISSUE TITLE
Trace support in google functions

### ISSUE THREAD

**Issue by SButterfly** [GoogleCloudPlatform/functions-framework-java#251]
Hello. I am struggling with how to add trace support to Google functions java SDK.

In my classpath I have added only `functions-framework-api`
```
    <dependency>
      <groupId>com.google.cloud.functions</groupId>
      <artifactId>functions-framework-api</artifactId>
    </dependency>
```

And implemented my custom function from `HttpFunction` interface.

But still, I don't see any traces in the trace-explorer.

**Comment by HKWinterhalter** [comment]
Hi @SButterfly, you may have seen this but here is the documentation around Tracing - https://cloud.google.com/trace/docs/overview

You may want to try using cloud logging client (Operations Suite) - https://cloud.google.com/logging/docs/reference/libraries

Please also see: https://cloud.google.com/functions/docs/monitoring/logging#processing_special_json_fields_in_messages and https://cloud.google.com/logging/docs/agent/logging/configuration#special-fields
