### ISSUE TITLE
functions-framework-api 1.1.1 release not available in Maven Central.

### ISSUE THREAD

**Issue by loicmathieu** [GoogleCloudPlatform/functions-framework-java#281]
See https://central.sonatype.com/artifact/com.google.cloud.functions/functions-framework-api

**Comment by jrmfg** [comment]
thanks for raising this, there was an issue with our release process because a non-existent plugin slipped in the 1.1.1 tag/release. i cut 1.1.2 with the fix and i'll check that it actually makes it to maven central.

**Comment by jrmfg** [comment]
1.1.2 had a problem releasing too. looking at this.

**Comment by dixuswe** [comment]
this versions is skipped and now at 1.1.4
