### ISSUE TITLE
Deploing Kotlin function with gradle build config

### ISSUE THREAD

**Issue by tomrozb** [GoogleCloudPlatform/functions-framework-java#36]
I'm trying to deploy the sample Kotlin function mentioned in readme file. This is the error I get - pom.xml is missing.

How should I use the gcloud deploy function to deploy functions with gradle config?

```
gcloud functions deploy justKotlinTest --entry-point functions.KotlinHelloWorld --runtime java11 --trigger-http --memory 512MB --allow-unauthenticated

Deploying function (may take a while - up to 2 minutes)...failed.                                                                       
ERROR: (gcloud.functions.deploy) OperationError: code=3, message=Build failed: Building user function from JAR
Function directory should contain either a pom.xml or a single *.jar file.
```

**Comment by glaforge** [comment]
Did you run the `gcloud` command in the directory where there's the `pom.xml` file or the JAR you want to deploy?

**Comment by tomrozb** [comment]
There's no/yes answer to your question, as there's no pom.xml file. As I mentioned I'm trying to deploy functions with Gradle instead of Maven. 

There's `build.gradle` in the root dir and the jar is located at `./build/libs/kotlin-functions-5-1.0-SNAPSHOT.jar `

**Comment by glaforge** [comment]
Right, yes, you have to be in the folder where the JAR (or pom.xml for those using Maven)
Feel free to suggest improvements to the docs or the README.

**Comment by MichelVHoward** [comment]
But i am having the problem that the dependencies say 
[NoClassDefFoundError: com/google/events/cloud/firestore/v1/DocumentEventData]
are not getting deployed ?
