### ISSUE TITLE
Support Signature Type: CloudEvent

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/functions-framework-java#37]
# Support signature type `cloudevent`

This signature type should support HTTP requests with CloudEvent objects delivered via either structured and binary CloudEvent objects. Usually a CloudEvents SDK can handle transforming the HTTP request to a language-native CloudEvent object.

[New signature `cloudevent` in **Functions Framework contract**](https://github.com/GoogleCloudPlatform/functions-framework#cloudevents-functions-signature-type-cloudevent)

The end-user should see the parameter `cloudevent`, which is a native CloudEvent object using the CloudEvent SDK if possible.

## Example User Experience (in Node)

```js
function handler(cloudevent) {
  console.log(cloudevent.id);
  console.log(cloudevent.data.message);
  console.log(cloudevent.custom_values_should_be_accepted);
  return "anything"
}
```

## Example HTTP requests

The CloudEvents specification requires support for both "binary" and "structured" encodings for CloudEvents delivered via HTTP. The Function Framework must support both encodings. A CloudEvents SDK might make this easier, but most SDKs are not complete, so logic may exist within the Framework.

Examples:

### Binary content mode

```json
POST /any/url/is/accepted HTTP/1.1
Host: example.com
ce-specversion: 1.0
ce-type: com.example.someevent
ce-time: 2018-04-05T03:56:24Z
ce-id: 1234-1234-1234
ce-source: /mycontext/subcontext
x-google-custom-header: 77
Content-Type: <contentType>
Content-Length: 33
{
    "message": "Hello World!"
}
```

### Structured content mode

```json
POST /someresource HTTP/1.1
Host: example.com
Content-Type: <contentType>
Content-Length: 266
{
    "specversion": "1.0",
    "type": "com.example.someevent",
    "time": "2018-04-05T03:56:24Z",
    "id": "1234-1234-1234",
    "source": "/mycontext/subcontext",
    "datacontenttype": "application/json",
    "data": {
        "message": "Hello World!"
    },
    "custom_values_should_be_accepted": 42
}
```

A user should be able to access all of the HTTP headers.
A user should be able to access the body of the CloudEvent in the `data` field of an object.

---

- Example PRs:
  - [Node](https://github.com/GoogleCloudPlatform/functions-framework-nodejs/pull/147)
  - [Go](https://github.com/GoogleCloudPlatform/functions-framework-go/pull/29)
  - [.NET](https://github.com/GoogleCloudPlatform/functions-framework-dotnet/pull/66)

**Comment by glaforge** [comment]
It still brings Jackson, Glassfish's EL and Hibernate Validator?
They should offer a shaded JAR so it appears as just one JAR, as things like Jackson and Validator are quite commonly used in Java projects :-(

**Comment by bsideup** [comment]
@glaforge after a loooooooooong conversation, we (Spring team members) have convinced the maintainer to split SDK into modules and extract `-api` that should only define the interfaces and have zero dependencies. The idea was to allow us provide our own implementation while being binary compatible with the rest of the world :D 
Compared to 1.x, the interfaces in 2.0 no longer use `Optional` (but nullability annotations) and have a plain structure (no `Attributes` sub-object). It reduces the memory pressure in high performant scenarios.

That said, 2.0 also includes pluggable json serialization (Jackson is a module now), and the validator dependency is removed.

**Comment by grant** [comment]
Can we use https://search.maven.org/artifact/io.cloudevents/cloudevents-api/2.0.0-milestone1/jar?

**Comment by eamonnmcmanus** [comment]
> Can we use https://search.maven.org/artifact/io.cloudevents/cloudevents-api/2.0.0-milestone1/jar?

Yes, I was intending to use that, with warnings in the javadoc that the API is subject to evolution.

**Comment by grant** [comment]
@eamonnmcmanus Can you give a general update as to support for CloudEvents? I think there is experimental support. Is this ready for use?

**Comment by eamonnmcmanus** [comment]
The published API supports defining a function that receives CloudEvents, and the Functions Framework code on GitHub includes the logic to send received CloudEvents to such a function. We need to make a release of the Functions Framework so that people can use that. I've also implemented translation from legacy GCF events to CloudEvents, which means that if you write a CloudEvents function, you can deploy it to GCF and it will be called even though GCF actually delivers the legacy events. But again that would need to be released before people can use it. We don't yet have the translation in the other direction, from CloudEvents to legacy GCF functions.

**Comment by eamonnmcmanus** [comment]
I'm going to close this issue. We do now support function handlers that receive CloudEvents, and they work even when the received event is a legacy event. The translation in the other direction, from CloudEvent to legacy event, is not yet implemented, but that should probably be tracked with a separate issue, and is within Google.
