### ISSUE TITLE
Incorrectly mapped parameter name for environment variable file for Maven Deploy plugin

### ISSUE THREAD

**Issue by jadn123** [GoogleCloudPlatform/functions-framework-java#39]
The `function.deploy.envvarsfile` is in the end mapped to `--env-var-file` which should instead be `--env-vars-file` (https://cloud.google.com/sdk/gcloud/reference/functions/deploy#--env-vars-file)

https://github.com/GoogleCloudPlatform/functions-framework-java/blob/d60ce1afdd98c0a7bebfa045ee3f9750d6db3b59/invoker/function-maven-plugin/src/main/java/com/google/cloud/functions/plugin/DeployFunction.java#L332

**Comment by martijnschouwe** [comment]
Yes bumped into the same issue:
Jun 18, 2020 1:17:15 PM com.google.cloud.tools.appengine.operations.Gcloud runCommand
SEVERE: ERROR: (gcloud.functions.deploy) unrecognized arguments: --env-var-file=.env.yaml (did you mean '--env-vars-file'?)
