### ISSUE TITLE
Maven -Drun.port CLI argument support

### ISSUE THREAD

**Issue by hearts-thaw** [GoogleCloudPlatform/functions-framework-java#43]
Documentation says that you can use "-Drun.port=" CLI argument for Maven to configure port that Functions Framework will use locally. It uses 8080 by default, but unfortunately it was already in use for me, so I've tried to change it through that feature.

But I was not able to. The thing is that it work for --port argument when using running with .jar. I've looked into the code and found out that RunFunction.java which is responsible for mapping CLI "-Drun." to "--" one argument doesn't have this lines of code specifically for port.

I've opened pull request to close this issue.

**Comment by hearts-thaw** [comment]
#44

**Comment by eamonnmcmanus** [comment]
Thanks for the PR, which I think does fix the problem.
