### ISSUE TITLE
Adding <port> is not working

### ISSUE THREAD

**Issue by AbhideepChakravarty** [GoogleCloudPlatform/functions-framework-java#49]
Hi,

I have added <port>8081</port> in my pom.xml , in the plugin configuration but still it does not pick it up and runs on default 8080. 

Regards,
Abhideep

**Comment by eamonnmcmanus** [comment]
Yes, this is a bug that was fixed by https://github.com/GoogleCloudPlatform/functions-framework-java/pull/44 but we haven't made a release with the fix yet.

**Comment by AbhideepChakravarty** [comment]
Thank you. I have noticed that it is working in your 0.9.5-SNAPSHOT version, when I forked it to debug. I would close this issue but I have a question and I will put it as a different issues.
