### ISSUE TITLE
Breaking change: Version 1.0.2 compiled for JDK 11

### ISSUE THREAD

**Issue by ilopmar** [GoogleCloudPlatform/functions-framework-java#55]
I've tried to upgrade from `1.0.1` to `1.0.2` version in Micronaut GCP module and the build fails to compile because version 1.0.2 has been compiled with JDK 11 instead of JDK 8.

See the error failure in our build: https://github.com/micronaut-projects/micronaut-gcp/pull/204/checks?check_run_id=1020154699#step:7:334

![image](https://user-images.githubusercontent.com/559192/91037647-aa088280-e609-11ea-91e1-ebc9d2d6c9c8.png)

I've also checked the `META-INF/MANIFEST.MF` for both versions from Central: https://repo.maven.apache.org/maven2/com/google/cloud/functions/functions-framework-api/

And the content is:

For `1.0.1`:
```
Manifest-Version: 1.0
Archiver-Version: Plexus Archiver
Created-By: Apache Maven 3.6.2
Built-By: emcmanus
Build-Jdk: 1.8.0_181-google-v7
```

For `1.0.2`:
```
Manifest-Version: 1.0
Archiver-Version: Plexus Archiver
Created-By: Apache Maven 3.6.3
Built-By: emcmanus
Build-Jdk: 11.0.4
```

This is a breaking change introduced in a patch release. Has this done on purpose or was it a mistake?

**Comment by jeffbrown** [comment]
It looks like this may have been introduced with the move to GitHub actions (#52).

**Comment by eamonnmcmanus** [comment]
This was a deliberate change. The Functions Framework is only supported on Java 11. That it used to work on Java 8 was a historical accident.

Could you give some background as to why you need it to work on Java 8?

**Comment by graemerocher** [comment]
our CI builds and tests against 8/11/14

It was surprising to us this changed in a patch release, but if this is by design then we will just adjust our CI. Thanks for the feedback

**Comment by ilopmar** [comment]
@eamonnmcmanus could it be possible to make those changes in another 2.x or 1.1 release and keep the current 1.0 compatible with JDK8? Without it we won't be able to upgrade to a new library version beyond 1.0.1.

**Comment by graemerocher** [comment]
@ilopmar since the functions runtime requires Java 11 I am not sure why this is the case?

**Comment by ilopmar** [comment]
Ohhh, wasn't aware of that...

**Comment by eamonnmcmanus** [comment]
Right, I should have communicated this better at the time. The principal target of this Functions Framework is currently Google Cloud Functions, and GCF does not support java8. Meanwhile retaining java8-compatible jars implied limiting the evolution of the framework, and in particular avoiding java11 language features and APIs. It also potentially could lead to confusion between local development and deployment. If you develop on java8 locally and then deploy to GCF, you'll be running on java11 there, and you could run into the numerous well-known incompatibilities between the two platforms.

Also, of course Java 8 is End Of Life and people should be looking to move off it, especially for things like GCF which typically don't involve running legacy code.

**Comment by m1ngyuan** [comment]
If spring cloud function wants to support cloud event like, but the project is still in jdk8, this means that spring-cloud-function-adapter-gcp is compiled on Java 11, which seems to be what the spring team is doing at present
