### ISSUE TITLE
Port option no take in account with maven plugin

### ISSUE THREAD

**Issue by fb64** [GoogleCloudPlatform/functions-framework-java#57]
Set port option in pom.xml file or in command line has no effect on function:run maven target. Invoker start always on 8080 port

```xml
<plugin>
    <groupId>com.google.cloud.functions</groupId>
    <artifactId>function-maven-plugin</artifactId>
    <version>0.9.4</version>
        <configuration>
            <functionTarget>myTarget</functionTarget>
            <port>9090</port>
        </configuration>
</plugin>
```

```shell
 com.google.cloud.functions:function-maven-plugin:0.9.4:run  -Drun.functionTarget=myTarget -Drun.port=9090
```

**Comment by torbenmoeller** [comment]
Same for me. I'm working on a bugfix right now.

**Comment by torbenmoeller** [comment]
It's actually already fixed in the current version. However the code hasn't been released as maven plugin yet.

**Comment by josephlewis42** [comment]
There have been several releases since the last comment here: https://central.sonatype.com/artifact/com.google.cloud.functions/function-maven-plugin/0.10.1?smo=true so I'm going to close this as fixed.
