### ISSUE TITLE
`HttpRequest.getPath()` does not include Function name (expected: `/my-gcp-function/helloworld/`, actual `/helloworld`)

### ISSUE THREAD

**Issue by aSemy** [GoogleCloudPlatform/functions-framework-java#90]
I've got a GCP Cloud Function, called `call-handler`. It's got a HTTP trigger. The trigger URL is 

```console
https://**location**projectname**.cloudfunctions.net/call-handler
```

I need to reconstruct the original URL that triggered `call-handler`. Let's say the original request is 

```console
https://**location**projectname**.cloudfunctions.net/call-handler/helloworld
```

When I log the output of `HttpRequest.getPath()`, it returns `/helloworld`, but I need it to be `/call-handler/helloworld`. This is what the Javadoc says it should be.

```console
The path part of the URI for this request, without any query. If the full URI is
{@code http://foo.com/bar/baz?this=that}, then this method will return {@code /bar/baz}.
```

The same goes for `HttpRequest.getUri()`. It returns `http://**location**projectname**.cloudfunctions.net/helloworld`. (Note that it returns `http`, which is why I need to reconstruct the original request.)

#### Issues

The Javadoc isn't accurate, or the code is bugged?

I've posted a work around below, but it would be really useful if this library provided helper functions to accurate generate all the information.

#### Workaround

A programmatic way of reconstructing the original request URL is to join these strings, in order

1. value of Header `X-Forwarded-Proto` ([docs for headers](https://cloud.google.com/appengine/docs/flexible/java/reference/request-headers))
2. `://`
3. value of Header `Host`
4. `/` (prefix for the cloud function name)
4. environment variable `K_SERVICE` ([docs for env-vars](https://cloud.google.com/functions/docs/env-var))
5. `HttpRequest.getPath()`: 
    1. IFF `getPath()` has 1 or more elements: prepend with `/`
    2. join each element with `/`
    3. Note: no trailing `/`
5. `HttpRequest.getQuery()`: 
    1. IFF `getQuery()` has 1 or more elements: prepend with `?`
    2. join each element with `&`

In my case, step by step it would be

1. `https`
2. `https://`
3. `https://**location**projectname**.cloudfunctions.net`
3. `https://**location**projectname**.cloudfunctions.net/`
4. `https://**location**projectname**.cloudfunctions.net/call-handler`
4. `https://**location**projectname**.cloudfunctions.net/call-handler/helloworld` \
    step by step of path construction:
    1. `/`
    5. `/helloworld` 
    6. ...
5. `https://**location**projectname**.cloudfunctions.net/call-handler/helloworld`  (no change, no query params)
    1. (`getQuery()` is empty)
    2. (no elements to join)

It was a lot of work to figure all that out, so I thought I'd share, in case it helps someone else.

**Comment by janell-chen** [comment]
The HttpRequest.getPath() is implemented by calling HttpServletRequest's getRequestURI() method, so this would not be related to a change needed in functions framework. 


https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#getRequestURI()
"Returns the part of this request's URL from the protocol name up to the query string in the first line of the HTTP request."

Similarly for getUri(), it calls the library's getRequestURL() and appends the query parameters if there are any.
Doc for getRequestURL(): "Reconstructs the URL the client used to make the request. The returned URL contains a protocol, server name, port number, and server path, but it does not include query string parameters."

**Comment by aSemy** [comment]
Hi @janell-chen, thanks for looking into this but I don't understand your reasoning. Why does the `HttpRequest.getPath()` say it will return one thing, but instead returns something else? It's confusing and problematic.
